flippy_mt_post: 1
flippy_head_mt_post: 0
flippy_show_empty_mt_post: 0
flippy_prev_label_mt_post: '[node:title]'
flippy_next_label_mt_post: '[node:title]'
flippy_first_last_mt_post: 0
flippy_first_label_mt_post: ''
flippy_last_label_mt_post: ''
flippy_loop_mt_post: 0
flippy_random_mt_post: 0
flippy_random_label_mt_post: ''
flippy_truncate_mt_post: ''
flippy_ellipse_mt_post: ''
flippy_press_swipe_mt_post: null
flippy_custom_sorting_mt_post: 1
flippy_sort_mt_post: nid
flippy_order_mt_post: ASC
