theme_select: block
alert_message: '(This is a demo message of the Module this theme is bundled with) This website uses cookies to help us provide you a better experience.'
target_url: 'http://www.morethanthemes.com'
_core:
  default_config_hash: _1tLvs-ARQfthz7yvI4K6-jWxKbvfybYYU66dTPn8lA
